Remove misleading text about passing arguments to env
TypeStrong/ts-node pull request #1448
Opened 2021-09-06 22:08 UTC by chee

gnu's `env` has a `-S` argument, which splits the string into command and arguments.

2021-09-06 22:13 UTC, cspotcode commented
Last I checked it's not available on all distros.  The relevant discussion might be in the issue tracker or in "discussions" somewhere; I'm not sure.

2021-09-06 23:21 UTC, chee commented
@cspotcode yeah, it's only been in GNU Coreutils since july 2018, so distros that have a 3+ year old version of gnu's `env` will not support it. the `-S` option is also needed for FreeBSD releases 6.0 and higher. `-S` is unsupported by OpenBSD, NetBSD and busybox.

2021-09-06 23:23 UTC, cspotcode commented
Ok thanks, is there some way we can either include that info in the docs, or link to a discussion

2021-09-06 23:25 UTC, cspotcode commented
Ok thanks for the detailed response.  Is there some way we can include that info in the docs, or link to a GH discussion thread with the details?  Could be something like "requires -S which is only on newer versions of env, see here (link to GH discussion) for details"

What do you think?

2021-09-16 22:45 UTC, cspotcode requested changes
Before we can merge, this will need the changes we talked about here:

> Ok thanks for the detailed response. Is there some way we can include that info in the docs, or link to a GH discussion thread with the details? Could be something like "requires -S which is only on newer versions of env, see here (link to GH discussion) for details"

2022-01-21 18:57 UTC, cspotcode commented
Making appropriate changes as part of #1545, but I'm linking to your compatibility notes in the docs.

2022-01-21 18:57 UTC, closed without merging